--1- database expioration
------------------------
select * from INFORMATION_SCHEMA.TABLES

select * from INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'dim_customers'

--2- dimensions exploration
-------------------------
--استكشف كل البلدان اللي بيجي منها العملاء 
SELECT DISTINCT country FROM dim_customers

--استكشف كل المنتجات داخل الشركه
SELECT DISTINCT category,subcategory FROM dim_products

--3- date exploration
-------------------
--find the date of the first and last order
SELECT
	MIN(order_date)AS first_order_date,
	MAX(order_date) last_order_date,
	--دي دالة بتديها السنتين وهي تطلع الفرق ما بينهم علي حسب السنين او الشهور
	DATEDIFF(year,MIN(order_date), MAX(order_date)) as order_range_years
FROM [dbo].[fact_sales]

--find the youngest and the oldest customer
SELECT
	MIN(birthdate) as oldest_customer,
	DATEDIFF(year, MIN(birthdate), GETDATE()) as age_oldest_customer ,
	MAX(birthdate) youngest_customer,
	DATEDIFF(year, MAX(birthdate), GETDATE()) as age_youngest_customer
FROM dim_customers

--4- measures exploration
--------------------------
--find the total sales 
SELECT SUM (sales_amount) AS Total_sales FROM fact_sales

--find how many items are sold 
SELECT SUM (quantity) AS Total_quantity FROM fact_sales

--find the average selling price
SELECT AVG (price) AS average_price FROM fact_sales

--find the total numbers of orders
SELECT COUNT (order_number) AS total_number FROM fact_sales
SELECT COUNT (DISTINCT order_number) AS total_number FROM fact_sales

--find the total numbers of products
SELECT COUNT ( product_number) AS total_products FROM dim_products
SELECT COUNT (DISTINCT product_number) AS total_products FROM dim_products

--find the total numbers of customer
SELECT COUNT (customer_number) AS total_customers FROM dim_customers
SELECT COUNT (DISTINCT customer_number) AS total_customers FROM dim_customers
--find the total numbers of customer that has placed an orders
SELECT COUNT ( customer_key) AS total_customers FROM dim_customers

-- generate a report that shows all key metrics of the business
SELECT 'Total_Seles' AS Measure_Name,SUM (sales_amount) AS Measure_Value FROM fact_sales
UNION ALL 
SELECT 'Total_Quantity' ,SUM (quantity) AS Measure_Value FROM fact_sales
UNION ALL 
SELECT 'Avg_Price' ,AVG (price) AS Measure_Value FROM fact_sales
UNION ALL 
SELECT 'Total_Order' ,COUNT (DISTINCT order_number) AS Measure_Value FROM fact_sales
UNION ALL 
SELECT 'Total_Product' ,COUNT (DISTINCT product_number) AS Measure_Value FROM dim_products
UNION ALL 
SELECT 'Total_Customers' ,COUNT (DISTINCT customer_number) AS Measure_Value FROM dim_customers

-- 5-Magnitude 
---------------
-- find total customer for countries
SELECT 
	country,
	COUNT (DISTINCT customer_number) AS Customer_Number
FROM dim_customers
GROUP BY country
ORDER BY customer_number DESC
-- find total customer by gender
SELECT 
	COUNT (DISTINCT customer_number) AS Customer_Number, 
	gender
FROM dim_customers
GROUP BY gender
-- find total products by category
SELECT 
	COUNT (DISTINCT product_number) AS Product_Numbers,
	category
FROM dim_products
GROUP BY category
-- what is the average costs in each category?
SELECT AVG(cost) AS Avg_cost , category
FROM dim_products
GROUP BY category
-- what is the total revenue generated for each category?
SELECT 
category ,
SUM([sales_amount]) AS total_revenue 
FROM fact_sales f
LEFT JOIN dim_products d
	ON f.product_key = d.product_key
GROUP BY category
ORDER BY total_revenue DESC
-- find total  revenue is generated by each customer
select  
d.customer_key,
d.first_name,
d.last_name,
SUM(f.sales_amount) AS Total_Revenua
from dim_customers as d
LEFT JOIN fact_sales as f
	on d.customer_key = f.customer_key
GROUP BY 
d.customer_key,
d.first_name,
d.last_name
ORDER BY Total_Revenua DESC
-- what is the distribution of sold items across cuontries ?
 SELECT 
	d.country,
	SUM (f.quantity) AS sold_items
 FROM dim_customers d
 LEFT JOIN fact_sales f
	ON d.customer_key = f.customer_key
GROUP BY d.country
ORDER BY sold_items DESC

-- 6- Rankig Analysis 
----------------------
-- Which 5 products generate the highest revenue ?
SELECT TOP 5
product_name ,
SUM([sales_amount]) AS total_revenue 
FROM fact_sales f
LEFT JOIN dim_products d
	ON f.product_key = d.product_key
GROUP BY product_name
ORDER BY total_revenue DESC

--What are the 5 worst-preforming products in terms of sales ?
SELECT TOP 5
product_name ,
SUM([sales_amount]) AS total_revenue 
FROM fact_sales f
LEFT JOIN dim_products d
	ON f.product_key = d.product_key
GROUP BY product_name
ORDER BY total_revenue 